name: familymap
description: "家人朋友位置共享 - 类Jagat果汁"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 地图
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # 网络 & 实时通信
  socket_io_client: ^3.0.2
  http: ^1.2.1

  # 位置服务
  geolocator: ^13.0.2

  # 状态管理
  provider: ^6.1.2

  # 本地存储
  shared_preferences: ^2.3.3

  # UI组件
  flutter_slidable: ^3.1.1

  # 工具
  uuid: ^4.5.1
  intl: ^0.20.1
  activity_recognition_flutter: ^6.0.0
  polylabel: ^1.0.1
  path_provider: ^2.1.5
  battery_plus: ^7.0.0
  flutter_local_notifications: ^22.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
